name: Call a reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: Wechoo/workflow-templates/.github/workflows/template-workflow.yml@master
