name: Calling a reusable workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  call-workflow:
    uses: Wechoo/workflow-templates/.github/workflows/template-workflow.yml@master
